### ISSUE TITLE
Change "Breeze" naming for building linux .deb package

### ISSUE THREAD

**Issue by FyreDemonyte** [BreezeHub/BreezeProject#17]
This change is being requested due to a package interference when installing this repo's BreezeProject as a .deb. 

Linux has a package in their main archive repository named "breeze" (see, [breeze package](https://launchpad.net/ubuntu/+source/breeze)). Thus when installing [Breeze.Wallet-v0.3.12-linux-amd64.deb](https://github.com/BreezeHub/BreezeProject/releases/download/v0.3.12/Breeze.Wallet-v0.3.12-linux-amd64.deb) the system thinks that it's the same package as the Ubuntu metapackage and automatically informs the user that an "update" is available for breeze to install: 
```
breeze:
  Candidate: 4:5.5.5-0ubuntu1
  Version table:
     4:5.5.5-0ubuntu1 500
```
@bokobza came across this situation as well, and can confirm my finding. 

Thus my recommendation to resolve this is to rename "Breeze" in https://github.com/BreezeHub/BreezeProject/blob/78984f2d4d18754428ce8526485a51c9cdcb1448/Breeze.UI/package.json#L2 To "Breeze Wallet" or the like.

**Comment by DanGould** [comment]
I was able to replicate this issue on 16.04. I'll let Pieterjan know and we'll repackage. Should be a quick fix.

**Comment by D3m0nKingx** [comment]
@DanGould Hi, this still needs to be corrected. I would do a PR but I don't know what name you guys want to agree on.
