### ISSUE TITLE
Stuck in Tor Warning

### ISSUE THREAD

**Issue by DanGould** [BreezeHub/BreezeProject#20]
![image](https://user-images.githubusercontent.com/8525467/34684669-e08b8ba2-f473-11e7-94c9-5d028ce7a5d0.png)

When one navigates to Privacy without running Tor, the OK button must redirect to History or Dashboard tab. Can't navigate away at the moment. It keeps popping up when dismissed

**Comment by DanGould** [comment]
@fenix2222 and I brainstormed some solutions. Best thing to do would probably be swap out "ok" with "back" which would bring you into another tab. an increasing time on connection attempts was also talked about

**Comment by fenix2222** [comment]
#23
